- name: Ensure Sqlcmd is installed and configured on Windows EC2
  hosts: windows
  gather_facts: no

  tasks:
    - name: Check if Sqlcmd is already installed
      win_stat:
        path: "C:\\Program Files\\sqlcmd\\sqlcmd.exe"
      register: sqlcmd_check

    - name: Install Chocolatey (only if Sqlcmd is absent)
      win_chocolatey:
        name: chocolatey
        state: present
      when: not sqlcmd_check.stat.exists

    - name: Install Sqlcmd using Chocolatey (if Sqlcmd is absent)
      win_chocolatey:
        name: sqlcmd
        state: present
      when: not sqlcmd_check.stat.exists

    - name: Ensure System32, Powershell and Sqlcmd exists in System Path
      win_environment:
        name: Path
        state: present
        level: machine
        value: "C:\\Windows\\System32;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\sqlcmd"
    
    - name: Reboot System to apply changes to the Environment
      win_reboot:
        msg: "Rebooting the system"
        reboot_timeout: 600
        connect_timeout: 600
        pst_reboot_delay: 60
      when: not sqlcmd_check.stat.exists
      ignore_errors: true

    - name: Wait for WinRM to become available after reboot
      wait_for_connection:
        timeout: 300

    - name: Confirm if sqlcmd is callable from Powershell
      win_shell: sqlcmd -?
      register: sqlcmd_output

    - name: Display sqlcmd Output
      debug:
        var: sqlcmd_output.stdout