name: Destroy Infrastructure CI Pipeline
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy Terraform Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: TerraFormTemplate
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::578160920339:role/bookstore-github-actions-oidc-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform init
      
      - name: Terrafrom Destroy
        run: terraform destroy -auto-approve